### ISSUE TITLE
Extension not compatible with eXist-db v5.0

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/jfreechart#24]
```
2019-05-05 14:12:35,815 [qtp1906335777-103] ERROR (EXistServlet.java [doGet]:285) - org.exist.validation.internal.node.NodeInputStream.<init>(Lorg/exist/storage/serializers/Serializer;Lorg/exist/xquery/value/NodeValue;)V 
java.lang.NoSuchMethodError: org.exist.validation.internal.node.NodeInputStream.<init>(Lorg/exist/storage/serializers/Serializer;Lorg/exist/xquery/value/NodeValue;)V
        at org.exist.xquery.modules.jfreechart.JFreeCharting.eval(JFreeCharting.java:153) ~[exist-jfreechart-0.4.jar:?]
        at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.LetExpr.eval(LetExpr.java:111) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.PathExpr.eval(PathExpr.java:276) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:261) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.xquery.XQuery.execute(XQuery.java:185) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1512) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
        at org.exist.http.RESTServer.doGet(RESTServer.java:520) ~[exist-core-5.0.0-RC8-SNAPSHOT.jar:5.0.0-RC8-SNAPSHOT]
```

**Comment by dizzzz** [comment]
closed by #25
